Refaktorert for å gjøre koden mer leselig og introdusert caching av arkivmeldinger mottatt
ks-no/gi-arkiv-2.0 pull request #63
Opened 2022-03-21 14:20 UTC by jarleborsheim

Har refaktorert en hel del for å gjøre det mer forståelig (håper jeg).
Det er nå også en slags cache som holder på de 10 siste arkivmeldinger som har en testSessionId som kommer inn til simulatoren. Da kan man ta opp igjen den arkivmeldingen som kom inn for hent, søk og oppdater meldinger. 
Dette støttes av at man putter på "testSessionId" på Fiks-IO meldingen som en header.

2022-03-22 10:30 UTC, exoen requested changes

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +        private static void HandleInnsynMelding(MottattMeldingArgs mottatt, bool xmlValidationErrorOccured)
`xmlValidationErrorOccured` kan fjernes som input i metoden da den blir overskrevet før den blir lest første gang

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +                    var sok = SokHandler.GetPayload(mottatt, sokXmlSchemaSet, out xmlValidationErrorOccured, out validationResult);
`out var` ... så kan null initialisering fjernes

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +        private static void HandleInnsynMelding(MottattMeldingArgs mottatt, bool xmlValidationErrorOccured)
Oppstår lett feil og forvirring med null initialisert variabler som skal bli satt med bruk av sideeffekt. Switch uttrykk skaper og lett forvirring hvis man glemmer  `break`. Foreslår å bruke `out var`, `return switch expressions` og lage metoder for å kommer seg bort fra sideeffekter så godt som mulig.

Forslag(Som trenger bedre navngivning): 

```
        private static void HandleInnsynMelding(MottattMeldingArgs mottatt)
        {
            Log.Information("Melding med {MeldingId} og meldingstype {MeldingsType} mottas", mottatt.Melding.MeldingId, mottatt.Melding.MeldingType);

            var payloads = new List<IPayload>();

            var melding = mottatt.Melding.MeldingType switch
            {
                ArkivintegrasjonMeldingTypeV1.Sok => ComputeSokMelding(mottatt),
                ArkivintegrasjonMeldingTypeV1.JournalpostHent => ComputeJournalPostHent(mottatt),
                _ => throw new ArgumentException("Case not handled")
            };
            
            payloads.Add(new StringPayload(ArkivmeldingSerializeHelper.Serialize(melding.ResultatMelding), melding.FileName));
            mottatt.SvarSender.Ack(); // Ack message to remove it from the queue
            
            var svarmsg = mottatt.SvarSender.Svar(melding.MeldingsType, payloads).Result;
            Log.Information("Svarmelding meldingId {MeldingId}, meldingType {MeldingType} sendt",  svarmsg.MeldingId, svarmsg.MeldingType );
            Log.Information("Melding er ferdig håndtert i arkiv");
        }

        private static Melding ComputeJournalPostHent(MottattMeldingArgs mottatt)
        {
            var journalpostHentXmlSchemaSet = new XmlSchemaSet();
            journalpostHentXmlSchemaSet.Add("http://www.arkivverket.no/standarder/noark5/journalpost/hent/v2",
                Path.Combine("Schema", "journalpostHent.xsd"));
            journalpostHentXmlSchemaSet.Add("http://www.arkivverket.no/standarder/noark5/metadatakatalog/v2",
                Path.Combine("Schema", "metadatakatalog.xsd"));
            
            var hentMelding = JournalpostHentHandler.GetPayload(mottatt, journalpostHentXmlSchemaSet,
                out var xmlValidationErrorOccured, out var validationResult);

            if (xmlValidationErrorOccured)
            {
                SendUgyldigforespoersel(mottatt, validationResult);
            }

            // Hent arkivmelding fra "cache" hvis det er en testSessionId i headere
            Arkivmelding arkivmelding = null;
            if (mottatt.Melding.Headere.TryGetValue(TestSessionId, out var testSessionId))
            {
                _arkivmeldingCache.TryGetValue(testSessionId, out arkivmelding);
            }

            return new Melding
            {
                ResultatMelding = arkivmelding == null
                    ? JournalpostHentGenerator.Create(hentMelding)
                    : JournalpostHentGenerator.Create(hentMelding, (Journalpost) arkivmelding.Registrering[0]),
                FileName = "resultat.xml",
                MeldingsType = ArkivintegrasjonMeldingTypeV1.JournalpostHentResultat
            };
        
    }

        private static Melding ComputeSokMelding(MottattMeldingArgs mottatt)
        {
            var sokXmlSchemaSet = new XmlSchemaSet();
            sokXmlSchemaSet.Add("http://www.ks.no/standarder/fiks/arkiv/sok/v1", Path.Combine("Schema", "sok.xsd"));

            var sok = SokHandler.GetPayload(mottatt, sokXmlSchemaSet, out var xmlValidationErrorOccured,
                out var validationResult);

            if (xmlValidationErrorOccured)
            {
                SendUgyldigforespoersel(mottatt, validationResult);
            }

            return ComputeMelding(sok);
        }

        private static Melding ComputeMelding(Sok sok) =>
            sok.ResponsType switch
            {
                ResponsType.Minimum =>
                    new Melding
                    {
                        FileName = "sokeresultat-minimum.xml",
                        MeldingsType = ArkivintegrasjonMeldingTypeV1.SokResultatMinimum,
                        ResultatMelding = SokeresultatGenerator.CreateSokeResultatMinimum(sok.Respons)
                    },
                ResponsType.Noekler =>
                    new Melding
                    {
                        FileName = "sokeresultat-noekler.xml",
                        MeldingsType = ArkivintegrasjonMeldingTypeV1.SokResultatNoekler,
                        ResultatMelding = SokeresultatGenerator.CreateSokeResultatNoekler(),
                    },
                ResponsType.Utvidet =>
                    new Melding
                    {
                        FileName = "sokeresultat-utvidet.xml",
                        MeldingsType = ArkivintegrasjonMeldingTypeV1.SokResultatUtvidet,
                        ResultatMelding = SokeresultatGenerator.CreateSokeResultatUtvidet(sok.Respons)
                    },
                _ =>
                    new Melding
                    {
                        FileName = "sokeresultat-minimum.xml",
                        MeldingsType = ArkivintegrasjonMeldingTypeV1.SokResultatMinimum,
                        ResultatMelding = SokeresultatGenerator.CreateSokeResultatMinimum(sok.Respons),
                    }
            };

        private class Melding
        {
            public string FileName { get; set; }
            public string MeldingsType { get; set; }
            public object ResultatMelding { get; set; }
        }
```

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +                Feilmelding = "Feilmelding:\n" + string.Join("\n ", validationResult[0]),
```suggestion
                Feilmelding = $"Feilmelding:{Environment.NewLine} {validationResult[0]}",
```

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +            var errorMessage = mottatt.SvarSender.Svar(FeilmeldingMeldingTypeV1.Ugyldigforespørsel,
Noe som hindrer for å fjerne `.Result` og bruke async await istede? selv om det vil boble oppover

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/Generators/JournalpostHentGenerator.cs
> +            } else if (journalpostHent.SystemID != null)
Hvorfor skal ikke `SystemId` bli satt hvis `ReferanseEksternNoekkel` har verdi? Eller skal det ikke være `else` med på linje 24?

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/Handlers/BaseHandler.cs
> +        protected static string GetPayloadAsString(MottattMeldingArgs mottatt, XmlSchemaSet xmlSchemaSet,
Ville opprettet et objekt `ValidationResult` som inneholder resultat, warning/error og isSuccess for å få vekk brukt av `out`

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/Handlers/BaseHandler.cs
> +            using (var inputStream = mottatt.Melding.DecryptedStream.Result)
`await`?

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/Handlers/JournalpostHentHandler.cs
> +            JournalpostHent journalpostHent = null;
fjern linje 19
returnere direkte på linje 31
return null på linje 35.

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/Handlers/SokHandler.cs
> +            return sok;
Enklere å få oversikt med direkte null return her

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/Validering/Validator.cs
> +                            Log.Information($"Mottatt vedlegg: {asiceReadEntry.FileName}");
```suggestion
                            Log.Information("Mottatt vedlegg: {FileName}", asiceReadEntry.FileName);
```

2022-03-22 10:30 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/Validering/Validator.cs
> +                    // Do something
Kanskje bare logge info go warning/error?

2022-03-22 12:35 UTC, jarleborsheim commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +        private static void HandleInnsynMelding(MottattMeldingArgs mottatt, bool xmlValidationErrorOccured)
Jepp. Ser den. Massiv refaktorering som har forårsaket dette tipper jeg. Bra observert.

2022-03-22 13:55 UTC, jarleborsheim commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +            var errorMessage = mottatt.SvarSender.Svar(FeilmeldingMeldingTypeV1.Ugyldigforespørsel,
Bra kommentarer her. Har fikset en del og må ta resten litt etter litt. Det er mye som bør fikses her men det bør kanskje tas litt etter litt 👍

2022-03-22 17:09 UTC, exoen approved these changes

2022-03-25 12:35 UTC, sturtzel commented
Denne kan dere fullføre uten at vi blander oss borti den (medfører ingen funksjonelle endringer som ikke har vært diskutert før). Evt. kommentarer får tas når vi tar koden i bruk.

2022-03-30 09:58 UTC, exoen approved these changes

2022-03-30 09:58 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +using EksternNoekkel = KS.Fiks.IO.Arkiv.Client.Models.Arkivering.Arkivmeldingkvittering.EksternNoekkel;
Fjern ubrukte usings

2022-03-30 09:58 UTC, exoen commented on dotnet-source/ks.fiks.io.arkivsystem.sample/ArkivSimulator.cs
> +            await Task.CompletedTask;
Kan fjerne async fra signatur med:
```suggestion
            return Task.CompletedTask;
```

2022-04-01 11:42 UTC, merged